//! IOCTL codes and device path — mirrors `shared/ndis_ioctl.h`.

pub const NDIS_USER_DEVICE_PATH: &str = "\\\\.\\WireSentinelNdis";
pub const NDIS_IOCTL_DEVICE_TYPE: u32 = 0x8020;
pub const NDIS_PROTOCOL_VERSION: u32 = 2;

const FILE_READ_DATA: u32 = 0x0001;
const FILE_WRITE_DATA: u32 = 0x0002;
const METHOD_BUFFERED: u32 = 0;

const fn ctl_code(device_type: u32, function: u32, method: u32, access: u32) -> u32 {
    (device_type << 16) | (access << 14) | (function << 2) | method
}

pub const IOCTL_NDIS_GET_DRIVER_STATE: u32 =
    ctl_code(NDIS_IOCTL_DEVICE_TYPE, 0x900, METHOD_BUFFERED, FILE_READ_DATA);
pub const IOCTL_NDIS_SET_ROUTE: u32 =
    ctl_code(NDIS_IOCTL_DEVICE_TYPE, 0x901, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_NDIS_CLEAR_ROUTE: u32 =
    ctl_code(NDIS_IOCTL_DEVICE_TYPE, 0x902, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_NDIS_SYNC_ROUTES: u32 =
    ctl_code(NDIS_IOCTL_DEVICE_TYPE, 0x903, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_NDIS_SET_TRANSFORM_PROFILE: u32 =
    ctl_code(NDIS_IOCTL_DEVICE_TYPE, 0x904, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_NDIS_SET_COVER_TRAFFIC: u32 =
    ctl_code(NDIS_IOCTL_DEVICE_TYPE, 0x905, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_NDIS_SYNC_REDIRECT: u32 =
    ctl_code(NDIS_IOCTL_DEVICE_TYPE, 0x906, METHOD_BUFFERED, FILE_WRITE_DATA);
pub const IOCTL_NDIS_GET_TELEMETRY_SUMMARY: u32 =
    ctl_code(NDIS_IOCTL_DEVICE_TYPE, 0x907, METHOD_BUFFERED, FILE_READ_DATA);
pub const IOCTL_NDIS_DRAIN_TELEMETRY: u32 =
    ctl_code(NDIS_IOCTL_DEVICE_TYPE, 0x908, METHOD_BUFFERED, FILE_READ_DATA);
pub const IOCTL_NDIS_CLASSIFY_PACKET: u32 =
    ctl_code(NDIS_IOCTL_DEVICE_TYPE, 0x909, METHOD_BUFFERED, FILE_WRITE_DATA);
